services:
  - type: worker
    name: telegram-finance-bot
    runtime: python
    buildCommand: ""
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: 8111564136:AAFwJaaTiG7VBAoU1GTeoOf5sAqkwiSIfgo
      - key: CANAL_ID
        value: -1002751312917

